version: '3.8'
services:
  rust-api:
    build: ./rust-api
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 5s
      timeout: 2s
      retries: 5
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: npm run dev
    healthcheck:
      test: ["CMD", "npm", "run", "healthz"]
      interval: 5s
      timeout: 2s
      retries: 5
    ports:
      - "3000:3000"
