version: '3.8'
services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 2s
      retries: 5
  rust-api:
    build: ./rust-api
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 5s
      timeout: 2s
      retries: 5
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: npm run dev
    healthcheck:
      test: ["CMD", "npm", "run", "healthz"]
      interval: 5s
      timeout: 2s
      retries: 5
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
